/*
 * Generated by STIR. Do not edit by hand.
 */

#include <sifteo/asset.h>

#pragma once

extern Sifteo::AssetGroup IconAssets;
extern const Sifteo::AssetImage Icon;
extern Sifteo::AssetGroup BootstrapAssets;
extern const Sifteo::PinnedAssetImage LabelLose;
extern const Sifteo::PinnedAssetImage BlackTile;
extern const Sifteo::PinnedAssetImage LabelTie;
extern const Sifteo::AssetImage Backgrounds;
extern const Sifteo::AssetImage IconPaper;
extern const Sifteo::AssetImage IconScissor;
extern const Sifteo::PinnedAssetImage LabelWin;
extern const Sifteo::AssetImage IconRock;
extern const Sifteo::AssetImage Silence;
extern const Sifteo::PinnedAssetImage BgTile;
extern const Sifteo::PinnedAssetImage StripeTile;
extern const Sifteo::AssetImage IconSandwich;
extern const Sifteo::AssetImage IconChroma;
extern const Sifteo::AssetImage IconPeano;
extern const Sifteo::AssetImage IconBuddy;
extern const Sifteo::AssetImage Tip0;
extern const Sifteo::AssetImage Tip1;
extern const Sifteo::AssetImage Tip2;
extern const Sifteo::AssetImage Footer;
extern const Sifteo::AssetImage LabelEmpty;
extern const Sifteo::PinnedAssetImage Bars[4];
extern const Sifteo::AssetAudio SfxAttach;
extern const Sifteo::AssetAudio SfxDetach;
extern const Sifteo::AssetAudio SfxConnect;
extern const Sifteo::AssetTracker Music;
